### ISSUE TITLE
multicast to .255

### ISSUE THREAD

**Issue by richardwilliamson** [ElectronicTheatreControlsLabs/OSCWidgets#2]
Hello

Am trying to set the output IP (with UDP) to 192.168.1.255 so that any device on the network that's listening can hear the message - I'm broadcasting to port 1000. When I hit connect the thread shows in the log as starting OK, however when I try to send a message I get "sendto failed with error 13" which as far as I can see is "permission denied" - I can send the message from qlab, and send a message from oscWidgets to the device using its specific IP address.

I'm on a mac running latest OS etc.

Thanks!

**Comment by richardwilliamson** [comment]
It looks like the SO_BROADCAST option needs to be set on the socket somehow..

**Comment by MizPlusPlus** [comment]
Yes, you are totally correct.  Fixed.  Thanks for the assist :+1:
