### ISSUE TITLE
Saving broke!

### ISSUE THREAD

**Issue by richardwilliamson** [ElectronicTheatreControlsLabs/OSCWidgets#5]
Hello
The new update doesn't seem to save/load properly, a colour seems to end up in the min1 box - on OSX at least.
Richard

**Comment by MizPlusPlus** [comment]
Sorry, you're right.  I see the typo, and will fix it tonight - thanks again for the feedback!

**Comment by MizPlusPlus** [comment]
Should be fixed in v0.5
