### ISSUE TITLE
Slow update of activity

### ISSUE THREAD

**Issue by richardwilliamson** [ElectronicTheatreControlsLabs/OSCWidgets#7]
I've noticed that the activity widgets seem to fade up/down when they change state, meaning that if there is a quick flow of data the widget struggles to keep up - I have been experimenting with a device that kicks out osc - on touchosc on iPad the equivalent control flashes at the appropriate speed but it's not quite so effective on this.

Is there a setting to control the fade? Or is it something deeper?

Thanks!

**Comment by MizPlusPlus** [comment]
I am just fading in and out over time.  I will make it a setting, so you can change it to be instantaneous...

**Comment by MizPlusPlus** [comment]
Tightened the default animation timing, and you can now shrink it even more with Min/Max2 fields

Thanks for the suggestion Richard :)
